version: "3.0"

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://185.177.216.63:5400/mhl
      - SPRING_DATASOURCE_USERNAME=mhl
      - SPRING_DATASOURCE_PASSWORD=5DrX2kpqfa
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8000:8000"

  pgbackups:
    container_name: backup
    image: prodrigestivill/postgres-backup-local
    restart: always
    volumes:
      - ./backup:/backups
    links:
      - db:db
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=mhl
      - POSTGRES_USER=mhl
      - POSTGRES_PASSWORD=5DrX2kpqfa
      - POSTGRES_EXTRA_OPTS=-Z9 --schema=public --blobs
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=5400