version: "3.0"

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://185.177.216.63:5400/mhl
      - SPRING_DATASOURCE_USERNAME=mhl
      - SPRING_DATASOURCE_PASSWORD=5DrX2kpqfa
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8000:8000"

  db:
    image: 'postgres:14.7-alpine'
    container_name: db
    environment:
      - POSTGRES_DB=mhl
      - POSTGRES_USER=mhl
      - POSTGRES_PASSWORD=5DrX2kpqfa
      - PGDATA=/var/lib/postgresql/data
    ports:
      - "5400:5400"
    command: -p 5400
    expose:
      - 5400
  pgbackups:
    container_name: backup
    image: prodrigestivill/postgres-backup-local
    restart: always
    volumes:
      - /var/opt/pgbackups:/backups
    links:
      - db
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=jdbc:postgresql:http://185.177.216.63:5400
      - POSTGRES_DB=mhl
      - POSTGRES_USER=mhl
      - POSTGRES_PASSWORD=5DrX2kpqfa
      - POSTGRES_EXTRA_OPTS=-Z9 --schema=public --blobs
      - SCHEDULE= * * * * *
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=5555